/*
 * This file is generated by jOOQ.
 */
package com.pracore.user.jooq;


import com.pracore.user.jooq.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>Technical Thursday</code> 
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_ROLE_ID = Indexes0.USERS_ROLE_ID;
    public static final Index USERS_USERS_ROLE_ID = Indexes0.USERS_USERS_ROLE_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERS_ROLE_ID = Internal.createIndex("role_id", Users.USERS, new OrderField[] { Users.USERS.ROLE_ID }, false);
        public static Index USERS_USERS_ROLE_ID = Internal.createIndex("users_role_id", Users.USERS, new OrderField[] { Users.USERS.ROLE_ID }, false);
    }
}
