/*
 * This file is generated by jOOQ.
 */
package com.pracore.user.jooq;


import com.pracore.user.jooq.tables.Roles;
import com.pracore.user.jooq.tables.Users;


/**
 * Convenience access to all tables in Technical Thursday
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Technical Thursday.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>Technical Thursday.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
