/*
 * This file is generated by jOOQ.
 */
package com.pracore.user.jooq;


import com.pracore.user.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in Technical Thursday
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Technical Thursday.users</code>.
     */
    public static final Users USERS = com.pracore.user.jooq.tables.Users.USERS;
}
