/*
 * This file is generated by jOOQ.
 */
package com.pracore.user.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.pracore.user.jooq.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TechnicalThursday extends SchemaImpl {

    private static final long serialVersionUID = 322842682;

    /**
     * The reference instance of <code>Technical Thursday</code>
     */
    public static final TechnicalThursday TECHNICAL_THURSDAY = new TechnicalThursday();

    /**
     * The table <code>Technical Thursday.users</code>.
     */
    public final Users USERS = com.pracore.user.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private TechnicalThursday() {
        super("Technical Thursday", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
