/*
 * This file is generated by jOOQ.
 */
package com.pracore.user.jooq;


import com.pracore.user.jooq.tables.Roles;
import com.pracore.user.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TechnicalThursday extends SchemaImpl {

    private static final long serialVersionUID = -1544431503;

    /**
     * The reference instance of <code>Technical Thursday</code>
     */
    public static final TechnicalThursday TECHNICAL_THURSDAY = new TechnicalThursday();

    /**
     * The table <code>Technical Thursday.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>Technical Thursday.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private TechnicalThursday() {
        super("Technical Thursday", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Roles.ROLES,
            Users.USERS);
    }
}
